# action.yml
name: 'Build image for tests'
description: 'Build the image to go through the pipeline'
inputs:
  check:
    description: 'Type of check to perform'
    required: true
    default: 'lint'
  dest:
    description: 'Destination directory inside workspace to output build-artifacts.'
    default: 'build'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  pre-entrypoint: '/app/tests/setup.sh'
  args:
    - ${{ inputs.check }}