name: Promote

on:
  repository_dispatch:
    types: [ promote ]

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{ version }}
          target_branch: master
          github_token: ${{ github.token }}
