name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag to promote'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: v${{ github.event.inputs.version }}
          target_branch: master
          github_token: ${{ github.token }}
