name: CI

on: 
  push:
    refs/heads:
      - master
      - staging
      - developement
      - contrib

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Iv pandas==0.23.3 flask-restful==0.3.6 requests==2.21.0 PyYAML==5.1 Babel==2.6.0 impyla==0.15a1 sklearn==0.0
        export PYTHONPATH=./app
    - name: Linting (pylint)
      run: |
        pip install -Iv pylint==2.4.4
        python ./lint/run_linter.py
    - name: Upload lint report to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: lint
        path: ./lint/report.txt
    - name: Unit testing
      run: |
        pip install -Iv nose2==0.9.1
        nose2 --config app/test/nose2.cfg --with-cov --coverage-report xml --coverage-config app/test/coverage/.coveragerc > app/test/report.txt 2>&1
    - name: Upload unit tests report to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: unittests
        path: ./app/test/report.txt
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
