name: QA

on: 
  push:
    refs/heads:
      - master
      - developement
      
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python3@v1
      - name: Lint (2)
        run: |
          pip3 install pylint  # -r requirements.txt
          pylint **/*.py --report=y --score=y --output-format=parseable # --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}"
      - name: Linting (pylint)
        uses: ./
        with:
          check: 'lint'
          dest: "app/test"
      - name: Upload lint report to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: lint
          path: ./report/lint.txt # ${INPUT_DEST}/lint.txt
    # - name: Unit testing
    #   run: |
    #     pip install -Iv nose2==0.9.1
    #     nose2 --config app/test/nose2.cfg --with-cov --coverage-report xml --coverage-config app/test/coverage/.coveragerc > app/test/report.txt 2>&1
      - name: Unit testing
        uses: ./
        # id: docker_build
        with:
          check: 'test'
          dest: "report"
      - name: Upload unit tests report to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: unittests
          path: ./report/test.txt
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
