name: QA

on: 
  push:
    refs/heads:
      - master
      - developement
      
jobs:
  test:
    # name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: toko-bifrost/ms-teams-deploy-card@master #  DO NOT set name.
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.ACTION_TEAMS_WEBHOOK }}
          show-on-exit: true
          # TODO - Check if it makes sense
          custom-actions: |
            - text: Promote
              url: "https://google.com"
      - name: Linting (pylint)
        uses: ./
        with:
          check: 'lint'
          dest: "report"
      - name: Upload lint report to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: lint
          path: ./report/lint.txt # ${INPUT_DEST}/lint.txt
      - name: Unit testing
        uses: ./
        with:
          check: 'test'
          dest: "report"
      - name: Upload unit tests report to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: unittests
          path: ./report/test.txt
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Bump version and push tag
        id: bump_tag
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: none # Check types in https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format
          tag_prefix: ""
      - name: Wait for Dockerhub to build the image
        run: |
          until curl -s https://hub.docker.com/v2/repositories/smartlab/datahub-api/tags/${{ steps.bump_tag.outputs.new_tag }} | grep -vq "errinfo"; do
            sleep 60
          done
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
          release_name: Release ${{ steps.bump_tag.outputs.new_tag }}
          body: ${{ steps.bump_tag.outputs.changelog }}
